// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vzfyafnyqasnrnqajpgb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6ZnlhZm55cWFzbnJucWFqcGdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMDAxNDYsImV4cCI6MjA2Mzg3NjE0Nn0.1NCYg-B_UxT6Sy_zvWP7a0TdmnBRGTM7-AGTQVGRAEk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);